- details:
    author: Robert Chetwyn
    date: 02/08/2021
    description: YAML configuration file for dynamic SQL environments
    vulnerability_type: boolean

- database:
      type: sqlite
      COMMENT#######: type examples | sqlite, MySQL, MongoDB
      max_tables: 3
      max_columns: 3
      randomised_content: 0
      include_standard: 0

- interaction:
    form_type: login
    COMMENT#######: form_type examples | login, interactive,
    real_world: 0
    randomised_content: 0

- security:
    security_level: 0
